### ISSUE TITLE
How about 2 pins on the same map?

### ISSUE THREAD

**Issue by AliMurtaza53** [pkmnct/qualtrics-google-map-lat-long#8]
In transportation, we often ask about a trip's origin and destination to responders. It'd be helpful if we had the origin(A) and destination(B)  both displayed on the same map and, also, if possible, connect the two with a dark line indicating the route like the ones we see in Google Maps when seeking directions.

Any ideas on how to have 2 addresses (pins) displayed on the same map? Thank you!

**Comment by forestbarnes** [comment]
I strongly support this feature as well! In our survey we asked participants the top three destinations they frequent within our study area and, on a separate page, the top three barriers for respondents to reach these destinations by bike. It would be helpful if, rather than showing three maps and labeling them location #1,2,3 we could instead display three search boxes with three different pins all shown on the **same** single map. The pins could still be dragable and would have the labels location #1,2,3. Alternatively, the pin icons could be circles with the numbers 1,2,3 in them for clarity.

**Comment by pkmnct** [comment]
@AliMurtaza53 @forestbarnes The beta 2.0 version of this script now supports multiple pins per map. If you are interested in giving it a try, see https://www.npmjs.com/package/qualtrics-google-map-lat-long. It is quite a bit different to configure compared to the 1.x versions of the script. If you do try it out, please provide any feedback you may have with the new version.

**Comment by pkmnct** [comment]
Version 2.0 has been released.
